apiVersion: v1
kind: Service
metadata:
  name: chatterbox-post-service
spec:
  selector:
    app: chatterbox-post-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer
